name: flutter_secure_storage
description: Flutter Secure Storage provides an API to store data in secure storage. Keychain is used in iOS, KeyStore-based solutions are used in Android, and WebCrypto is utilized for web.
version: 9.2.3
repository: https://github.com/mogol/flutter_secure_storage/tree/develop/flutter_secure_storage

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.it_nomads.fluttersecurestorage
        pluginClass: FlutterSecureStoragePlugin
      ios:
        pluginClass: FlutterSecureStoragePlugin
      linux:
        default_package: flutter_secure_storage_linux
      macos:
        default_package: flutter_secure_storage_macos
      web:
        default_package: flutter_secure_storage_web
      windows:
        default_package: flutter_secure_storage_windows

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_linux: ^1.2.1
  flutter_secure_storage_macos: ^3.1.2
  flutter_secure_storage_platform_interface: ^1.1.2
  flutter_secure_storage_web: ^2.0.0-beta.1 # Updated to Wasm-compatible version
  flutter_secure_storage_windows: ^3.1.2
  meta: ^1.8.0 # Latest version for improved null safety and compatibility

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.0

platforms:
  android:
    pluginClass: FlutterSecureStoragePlugin
  ios:
    pluginClass: FlutterSecureStoragePlugin
  linux:
    pluginClass: FlutterSecureStorageLinux
  macos:
    pluginClass: FlutterSecureStorageMacOS
  web:
    pluginClass: FlutterSecureStorageWeb
  windows:
    pluginClass: FlutterSecureStorageWindows
