name: flutter_secure_storage_web
description: Web implementation of flutter_secure_storage. Use flutter_secure_storage for the full Flutter package.
repository: https://github.com/mogol/flutter_secure_storage
version: 2.0.0-beta.2 # Incremented version for clarity after updates.

environment:
  sdk: ">=3.3.0 <4.0.0" # Updated to match modern Dart requirements.
  flutter: ">=3.19.0"   # Ensures compatibility with Flutter 3.19.0 and above.

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface: ^1.1.2 # Updated to match federated plugin best practices.
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0 # Updated dependency range to avoid conflicts with other packages.

dev_dependencies:
  lint: ^2.2.0 # Updated linting tool for modern Dart/Flutter practices.

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterSecureStorageWeb
        fileName: flutter_secure_storage_web.dart
