name: flutter_secure_storage_platform_interface
description: A common platform interface for the flutter_secure_storage plugin.
homepage: https://github.com/mogol/flutter_secure_storage
version: 1.1.2

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0
  mockito: ^5.0.12